In [3]:
import ast, json
import pandas as pd



# load CSV summary
summary = pd.read_csv("outputs/recon_summary.csv")
summary["columns_different"] = summary["columns_different"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") else x
)
display(summary.sort_values(["priority","cash_impact"], ascending=[False, False]).head(50))

# load JSONL details
records = [json.loads(line) for line in open("outputs/recon_details.jsonl","r",encoding="utf-8")]
detail_df = pd.json_normalize(records)
display(detail_df)

,event_key,account,isin_nb,isin_cu,columns_different,cash_impact,reason_code,priority,explanation,suggested_fix
0,960789012,712345678,KR7005930003,KR7005930003,"[net_qc, net_sc, tax_amt, tax_rate]",450050.0,NET_AMOUNT_MISMATCH,3,The net amounts in the custody and NBIM record...,Review the net amounts reported in both system...
1,970456789,823456790,CH0038863350,CH0038863350,[nominal],15000.0,NOMINAL_POSITION_MISMATCH,3,The nominal position differs between the two a...,Review the nominal position entries for both a...
2,970456789,823456791,CH0038863350,CH0038863350,"[gross_qc, net_qc, net_sc, tax_amt]",6200.0,GROSS_QC_MISMATCH,3,The gross amount in the custody record differs...,Investigate the source of the gross amount dis...

,payload.event_key,payload.account,payload.isin_nb,payload.isin_cu,payload.ex_date_nb,payload.ex_date_cu,payload.pay_date_nb,payload.pay_date_cu,payload.qc_nb,payload.qc_cu,...,payload.diffs.pay_date_days_diff,payload.diffs.ex_date_days_diff,payload.different_fields,payload.cash_impact,classification.reason_code,classification.explanation,classification.suggested_fix,classification.priority,classification.evidence_fields,classification.notes
0,960789012,712345678,KR7005930003,KR7005930003,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-05-20 00:00:00+00:00,2025-05-20 00:00:00+00:00,KRW,KRW,...,0,0,"[net_qc, net_sc, tax_amt, tax_rate]",450050.0,NET_AMOUNT_MISMATCH,The net amounts in the custody and NBIM record...,Review the net amounts reported in both system...,3,"[net_qc, net_sc, tax_amt, tax_rate]",
1,970456789,823456790,CH0038863350,CH0038863350,2025-04-25 00:00:00+00:00,2025-04-25 00:00:00+00:00,2025-04-29 00:00:00+00:00,2025-04-29 00:00:00+00:00,CHF,CHF,...,0,0,[nominal],15000.0,NOMINAL_POSITION_MISMATCH,The nominal position differs between the two a...,Review the nominal position entries for both a...,3,[nominal],
2,970456789,823456791,CH0038863350,CH0038863350,2025-04-25 00:00:00+00:00,2025-04-25 00:00:00+00:00,2025-04-29 00:00:00+00:00,2025-04-29 00:00:00+00:00,CHF,CHF,...,0,0,"[gross_qc, net_qc, net_sc, tax_amt]",6200.0,GROSS_QC_MISMATCH,The gross amount in the custody record differs...,Investigate the source of the gross amount dis...,3,"[gross_qc, net_qc, net_sc, tax_amt]",